### PR TITLE
Fix Keyboard Functionality

### PR DESCRIPTION
**Pull request by mohamedhesham221**
Summary of the Changes:
I applied several updates to the virtual keyboard project, primarily focused on improving the layout, animations, and handling key events more effectively.
- CSS Changes: Centered the content vertically and horizontally.
- HTML Changes: Updated the HTML structure to ensure that the correct CSS files are linked and adjusted the layout to support the updated animations.
- JavaScript Changes: Improved the handling of key events, including handling both click and `keydown`/`keyup` events more efficiently, ensuring the correct display of keys and their effects.

### CODE REVIEW

**Comment by brgkdm** [comment]
> Summary of the Changes: I applied several updates to the virtual keyboard project, primarily focused on improving the layout, animations, and handling key events more effectively.
> 
> * CSS Changes: Centered the content vertically and horizontally.
> * HTML Changes: Updated the HTML structure to ensure that the correct CSS files are linked and adjusted the layout to support the updated animations.
> * JavaScript Changes: Improved the handling of key events, including handling both click and `keydown`/`keyup` events more efficiently, ensuring the correct display of keys and their effects.
#
I would like to express my gratitude for your efforts. The issue I previously raised seems to have been resolved. However, I would like to request a small adjustment:

Kindly remove the functionality where a letter (or text) is displayed below the keys when they are clicked. I would prefer that only the key highlights remain visible on the screen.

Additionally, and as an optional request:

When a key is pressed on the physical keyboard, some of the corresponding virtual keys on the screen are either not being activated, or are highlighted incorrectly. If you could address this issue, it would greatly contribute to the development of the project.
Thank you once again, and I wish you continued success in your work.

**Comment by mohamedhesham221** [comment]
Thank you for your feedback and kind words! I’m glad the main issue has been resolved.

I’ll review the functionality to remove the text display below the keys and ensure that only the key highlights remain visible. I’ll also investigate the issue with incorrect or missing highlights for some virtual keys when pressing physical keys.

Once I’ve made the adjustments, I’ll update you.

**Comment by brgkdm** [comment]
There is something wrong with this. @mohamedhesham221 

How does it look on you?

https://github.com/user-attachments/assets/111bb56c-b5bf-4dad-b911-9f37eec44197

**Comment by mohamedhesham221** [comment]
I think it works as expected now 
### What I did
- I used Your custom attribute `data-key` instead of `innerText` for detecting the actual element because innerText only returns the first element in special characters (shift, alt, etc.) in DOM tree
- [MDN: Node Interface](https://developer.mozilla.org/en-US/docs/Web/API/Node)
- [MDN: Element.innerText](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/innerText)
### Suggestion
- If you want to make it quick and easy and without any tricky things just modify your `data-key` value for all buttons to match `event.code` not `event.key` as you did in special characters

**Comment by brgkdm** [comment]
> I think it works as expected now
> 
> ### What I did
> * I used Your custom attribute `data-key` instead of `innerText` for detecting the actual element because innerText only returns the first element in special characters (shift, alt, etc.) in DOM tree
> * [MDN: Node Interface](https://developer.mozilla.org/en-US/docs/Web/API/Node)
> * [MDN: Element.innerText](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/innerText)
> 
> ### Suggestion
> * If you want to make it quick and easy and without any tricky things just modify your `data-key` value for all buttons to match `event.code` not `event.key` as you did in special characters

Hello, I hope you are doing well. When I check the project, I can't get any functionality. I don't understand what's the problem.

**Comment by mohamedhesham221** [comment]
What errors did you get in the console?

**Comment by brgkdm** [comment]
> What errors did you get in the console?

image

**Comment by mohamedhesham221** [comment]
Did you update the code from the last changes i committed ?

**Comment by brgkdm** [comment]
> Did you update the code from the last changes i committed ?

I just made a small update and I didn't see any problems. Thank you for your contribution, I'm adding it to the project.

**Comment by mohamedhesham221** [comment]
I am glad to hear that, and can you share what update you did ?

**Comment by brgkdm** [comment]
> I am glad to hear that, and can you share what update you did ?

https://github.com/brgkdm/KeyboardFX/commit/19d4f25cc30b1c3d446bcd62ed9448d6097b4eea

**Pull request merged**
